//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectingLogs
    {
        public int ConnectingLog_ID { get; set; }
        public string ConnectingLog_HostName { get; set; }
        public string ConnectingLog_IP { get; set; }
        public bool ConnectingLog_IsPermit { get; set; }
        public string ConnectingLog_Error { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
